eco-dessert-platform/dessert-front

tailwind.config.js
> ex) #이슈번호
e.g
```tsx
<div className="typo-body-11-bold">
text
</div>
```
=> ✨ Feat : typo 가이드 작성

tailwind.config.js
> ex) #이슈번호
실수로 누락된 typo 속성 추가했습니다.
=> 🐛 Fix :  typo 없는 속성 추가

src/app/wish/@login/default.tsx, tailwind.config.js
> ex) #이슈번호
letter-spacing 값 잘못 들어가서 수정했습니다.
=> 🐛 Fix :  letter-spacing 수정

.github/workflows/chromatic.yml
> ex) #이슈번호
환경변수가 제대로 읽히지 않는 버그 수정했습니다.
=> 👷 Build :  크로마틱 환경변수 설정 오류 해결

src/domains/wish/queries/service.ts, src/domains/wish/queries/useWishStoreListQuery.ts
> ex) #이슈번호
찜 스토어 조회 API cursor로 리팩토링되어 적용했습니다.
=> ♻️ Refactor :  wish store 조회 cursor 적용

src/app/search/(intro)/layout.tsx, src/domains/search/components/AutoCompleteSearchContainer/AutoCompleteSearchItem.tsx, src/domains/search/components/PopularKeyword.tsx, src/domains/search/components/RecentKeyword.tsx, src/domains/search/components/SearchInput.tsx
> ex) #이슈번호
close #344 
검색 페이지 typo 수정했습니다
=> 💄 Design: 검색 페이지 typo 수정

env.d.ts, package.json, src/app/ga-test/page.tsx, src/app/layout.tsx, src/blocks/home/HomeLogoSection.tsx, src/global/GAScript.tsx, yarn.lock
> ex) #이슈번호
google analytics 연동중인데,
배포 환경에서 테스트 해봐야해서  ga test page 추가 했습니다.
=> ✨ Feat :  google analytics script, test page 추가

tailwind.config.js
=> 🚑️ Hotfix:  tailwind config 오타 수정

.github/workflows/pr-check-code.yml
=> 🐛 Fix :  pr check github action

.vscode/setting.json, .vscode/settings.json, .yarnrc.yml
> ex) #이슈번호
yarn 관련 버그 수정하면서 prettier 제대로 동작하지 않는 문제 생겨서 해결했습니다
=> 📦️ Chore :  프리티어 버그 수정

src/domains/store/hooks/useGetStoreDetailAllQuery.ts, src/domains/store/hooks/useGetStoreDetailQuery.ts, yarn.lock
>close #337
> 
스토어 상세 페이지 api 응답 리팩토링하였습니다.
github action 때문에 이전 pr close 하고 같은 내용으로 다시 올립니다
=> ♻️ Refactor :  스토어 상세 api 리팩토링

src/domains/store/components/StoreCard.tsx, src/domains/store/queries/useGetAllStoresQuery.ts, src/domains/store/types/allStoresType.ts
> ex) #이슈번호
- `useGetAllStoresQuery` 훅 수정
- `StoreCard` 링크 추가
=> 🐛 Fix : `useGetAllStoresQuery` 훅 수정, `StoreCard` 링크 추가

src/app/mypage/(policy)/notifications/page.tsx, src/domains/user/queries/service.ts, src/domains/user/queries/useGetAllNotificationsQuery.ts, src/shared/constants/corsor.ts, src/shared/queries/service.ts
> ex) #이슈번호
- corsorId가 잘 못 설정 되어 있어서 수정했습니다.
- initialPageParam 에 쓰이는 `-1` 상수화 했습니다.
- Service의 fetchExtend 버그 수정했습니다.
=> 🐛 Fix : 공지사항 API 버그 수정

.eslintrc.json
=> 📦️ Chore :  any 금지

src/shared/components/Dropdown/DropdownContent/DropdownItem.tsx, src/shared/components/Dropdown/DropdownContent/index.tsx, src/shared/components/Dropdown/DropdownTrigger.tsx, src/shared/components/Dropdown/index.stories.tsx, src/shared/components/Dropdown/index.test.tsx, src/shared/components/Dropdown/index.tsx, src/shared/hooks/useToggle.tsx, src/shared/utils/getComponent.tsx, tailwind.config.js
> ex) #이슈번호
리뷰 컴포넌트 점점점 버튼 구현하기위해서 Dropdown 부터 구현하였습니다.
```tsx
<Dropdown>
<Dropdown.Trigger>트리거</Dropdown.Trigger>
<Dropdown.Content>
<Dropdown.Item>메뉴1</Dropdown.Item>
<Dropdown.Item>메뉴2</Dropdown.Item>
<Dropdown.Item>메뉴3</Dropdown.Item>
</Dropdown.Content>
</Dropdown>
```
=> ✨ Feat :  Dropdown 구현

public/assets/icons/kebab.svg, src/domains/review/components/Review/index.tsx, src/shared/components/Dropdown/DropdownContent/index.tsx, src/shared/components/Dropdown/index.tsx, src/shared/components/icons/index.tsx, src/shared/constants/path.ts
> ex) #이슈번호
- 리뷰 더보기(kebab) UI 구현했습니다.
- Dropdown.Content
`position` prop 추가했습니다.
=> ✨ Feat :  리뷰 더보기(kebab) UI

src/app/main/(detail)/products/[productId]/review/[reviewId]/layout.tsx, src/app/main/(list)/layout.tsx, src/blocks/wish/(list)/products/WishHeader.tsx
> ex) #이슈번호
useSearchParams 사용하는 컴포넌트는 꼭 Suspense로 감싸주세요!
build시 에러 납니다.
참고: https://nextjs.org/docs/messages/missing-suspense-with-csr-bailout
=> 🚑️ Hotfix:  Suspense 추가(useSearchParams)

.github/workflows/auto-deploy.yml
=> 📦️ Chore : ga 환경변수 추가

.github/workflows/chromatic.yml, .github/workflows/pr-check-code.yml, src/blocks/home/BestProductsSection/ProductsList.tsx
> ex) #이슈번호
- lint 에러 수정
- pr check `yarn lint-staged` ->`yarn lint` 변경
- 스토리북 배포 stoires 파일 변화가 있을때만 수행
=> 🚑️ Hotfix:  lint

src/blocks/home/BestProductsSection/TitleSection.tsx
> ex) #이슈번호
`userService.getPreference()`에서 에러를 던질 때 홈페이지 전체가 다운되는 건 좋지 않은 것 같아서 try-catch 처리해줬습니다.
치명적인 버그는 아닌 것 같아 일단 fix로 pr 올렸고, '상품 리뷰' pr 머지될 때 같이 배포되면 될 것 같아요.
=> 🐛 Fix : `getPreference` api 에러 처리

src/global/GAScript.tsx
=> ✨ Feat :  GTM script추가

env.d.ts, src/global/GAScript.tsx
> ex) #이슈번호
환경 변수 gtm id 값이 잘 못 들어가서 수정
=> 🚑️ Hotfix:  gtm

src/app/mypage/login/google-login/page.tsx, src/app/mypage/login/kakao-login/page.tsx
=> 🚑️ Hotfix:  소셜로그인 버그(webview)

src/shared/utils/dictionary/index.test.ts, src/shared/utils/dictionary/index.ts
> ex) #이슈번호
transfrom~~ 코드 가독성이 너무 안 좋음
transformCategoryToEng
transformCategoryToKr 등
양방향으로 변환 가능한 Dictionary 
```ts
const dictionary = new Dictionary({
glutenFree: "글루텐프리",
sugarFree: "저당"
})
dictionary.tranlsate("glutenFree"); // returns "글루텐프리"
dictionary.tranlsate("글루텐프리"); // returns "glutenFree"
```
=> ✨ Feat :  양방향 변환 가능한 Dictionary class 작성

next.config.js
=> 🚑️ Hotfix:  kakaocnd 허용

next.config.js
=> 🚑️ Hotfix:  kakaocnd 허용 (#486)

src/app/(with-navigation)/mypage/login/page.tsx, src/app/mypage/login/google-login/page.tsx, src/app/mypage/login/kakao-login/page.tsx
=> 🚑️ Hotfix/window.close error (#488)

src/app/review/[productId]/create/[progress]/page.tsx, src/domains/review/components/ReviewWriteForm/CommentSection/StarRatingSection.tsx
> ex) #이슈번호
product option API를 실수로 호출 해서
product detail API로 바꾸었습니다.
=> 🐛 Fix :  review title 수정

src/shared/utils/metadata.ts, yarn.lock
- #502 
현재 Front에서 
- `Dev` ( https://www.bbangle.store/ )
- `Main` ( https://www.bbanggree.com/ )
각각 별도의 도메인과 branch를통해 배포 및 관리되어지고 있는 것을 확인하였습니다.
또한 각 배포 환경 모두 동일한 Meta 설정 및 SEO 설정이 적용되어있는것으로 확인하였습니다.
이로인해 예상 되어지는 문제로는
- 현재 `metadataBase` 의 값을 https://www.bbanggree.com/ 변경하였지만 그와 별개로, 기존 Dev ( https://www.bbangle.store/ )환경의 SEO가 우선 시 되어 현재의 문제가 발생하지 않을까 예상되어집니다.
이런 문제로 "빵그리의 오븐" 키워드로 검색 진행 시 동일한 페이지 내부에 아래와 같은 두 가지의 도메인이 모두 제공되어지는 문제가 발생하지 않았나 예상되어집니다.
**Dev 환경의 서비스**
**Main 환경의 서비스**
Dev 배포 환경과 Main 배포 환경을 구분하고, Main 배포 환경에서만 Meta 데이터가 제공될 수 있도록 환경 변수를 통해 제어하였습니다.
```
NEXT_PUBLIC_DEV_SETTING=false
```
```tsx
const IS_DEV_MOD: boolean = JSON.parse(process.env.NEXT_PUBLIC_DEV_SETTING ?? 'false');
export const getStaticMetadata = (route: StaticRoute): Metadata => {
if (IS_DEV_MOD) return …
```
=> Fix : SEO > Dev 환경과 Main 환경 분리

src/app/robots.ts
- #528 
- close #528 
현재 Dev 환경이 배포되어있는 도메인 bbangle.store에 대한 크롤링을 차단하기 위해 robots.txt 설정
```tsx
export default function robots(): MetadataRoute.Robots {
// Dev 환경에서 모든 서비스 경로에 대해 크롤링 차단
if (IS_DEV_MODE) {
return {
rules: {
userAgent: '*',
disallow: '/'
}
};
}
return {
rules: {
userAgent: '*',
allow: '/'
}
};
}
```
SEO에 대해 빠르게 테스트 해보기 위해 추가적인 작업 후 빠르게 PR올려봅니다.
SEO 에 대한 테스트가 끝난 후 현재 환경 변수에 대해 DEV 환경을 구분하는 로직에 대해 좀 더 깔끔하게 개선해 보면 좋을 것 같습니다!
```tsx
const IS_DEV_MODE = JSON.parse(process.env.NEXT_PUBLIC_DEV_SETTING ?? 'false');
```
해당 부분이 계속 눈에 밟히네요 ㅠ AWS 배포 부분을 잘 수정하면 편하게 환경변수 값을 사용할 수 있을것 같습니다.
=> ✨ Feat :  robots 적용

src/app/main/products/[productId]/info/_blocks/SimpleInfoWithStoreSection/DetailStoreInfo/index.tsx, src/blocks/main/(detail)/products/[productId]/info/SimpleInfoWithStoreSection/DetailStoreInfo.tsx, src/domains/store/components/StoreCard.tsx, src/domains/wish/queries/useAddWishProductMutation.tsx, src/domains/wish/queries/useAddWishStoreMutation.ts
- #535 
close #535 
- 맨 처음 기본 폴더에 추가될 때 기본 폴더에 대한 메세지 제공
- 스토어 추가 시 추가 된 스토어의 이름 동적 제공
=> 🐛 Fix :  스토어 추가 및 제거 동적 메세지 전달

src/middleware.ts
- #555 
close #555 
Middleware.ts를 통해 현재 사용자가 접근 가능한 경로인가? 에 대한 예외 처리 추가
- cookie내부 accessToken의 여부를 검사하여 인증된 사용자인지에 대해 판별
- 이후 비 로그인시 접근 불가능 한 경로 추가 및 Home으로 리다이렉션
```tsx
import { cookies } from 'next/headers';
import { NextRequest, NextResponse } from 'next/server';
export const middleware = async (request: NextRequest) => {
const { pathname } = request.nextUrl;
const accessToken = cookies().get('accessToken')?.value || null;
// 토큰 존재 여부 판별
if (pathname.startsWith('/review') && !accessToken) {
return NextResponse.redirect(new URL('/', request.url));
}
// 기존 이동 경로 및 다음 동작 실행
return NextResponse.next();
};
```
=> ✨ Feat :  Middleware.ts 추가

.eslintrc.json, src/app/main/products/[productId]/info/_blocks/ProductOptionsSection/IngredientInfo.tsx, src/app/main/products/[productId]/info/_blocks/ProductOptionsSection/NutrientInfo.tsx, src/app/main/products/[productId]/layout.tsx, src/app/main/products/[productId]/review/_blocks/BadgeSection.tsx, src/domains/product/utils/transfromTag.ts, src/shared/components/TopButton.tsx, yarn.lock
Reverts eco-dessert-platform/dessert-front#568
=> Revert "♻️Refactor : 상품 상세 페이지 개선 "

src/app/(with-navigation)/landing/page.tsx, src/app/main/products/[productId]/info/_blocks/ProductOptionsSection/IngredientInfo.tsx, src/app/main/products/[productId]/info/_blocks/ProductOptionsSection/NutrientInfo.tsx, src/app/main/products/[productId]/info/_blocks/SimpleInfoWithStoreSection/DetailStoreInfo/index.tsx, src/app/main/products/[productId]/review/_blocks/BadgeSection.tsx, src/blocks/store/StoreInfoSection.tsx, src/blocks/user/UserInfoSection.tsx, src/domains/product/utils/transfromTag.ts, src/domains/user/components/common/ProfileImageInput/PreviewImage.tsx, src/shared/components/DefaultLayout/index.tsx, src/shared/components/ImageWithFallback/index.tsx, src/shared/components/TopButton.tsx
> 
> 
- next 이미지 unoptimzed 설정 추가해놨던 부분 전부 제거
- 상세페이지 탭헤더 상단고정을 위해 defaultlayout에 height 지정
- 이전 커밋작업 merge
=> fixed: 이미지 최적화 설정

.eslintrc.json, src/app/(with-navigation)/landing/page.tsx, src/app/main/products/[productId]/info/_blocks/ProductOptionsSection/IngredientInfo.tsx, src/app/main/products/[productId]/info/_blocks/ProductOptionsSection/NutrientInfo.tsx, src/app/main/products/[productId]/info/_blocks/SimpleInfoWithStoreSection/DetailStoreInfo/index.tsx, src/app/main/products/[productId]/review/_blocks/BadgeSection.tsx, src/blocks/store/StoreInfoSection.tsx, src/blocks/user/UserInfoSection.tsx, src/domains/product/utils/transfromTag.ts, src/domains/user/components/common/ProfileImageInput/PreviewImage.tsx, src/shared/components/DefaultLayout/index.tsx, src/shared/components/ImageWithFallback/index.tsx, src/shared/components/TopButton.tsx, src/shared/utils/metadata.ts
=> fixed: 메타데이터 dev 조건문 제거

src/domains/product/components/ProductCard/ProductImage/index.tsx
https://github.com/eco-dessert-platform/dessert-front/issues/578
=> 🐛 Fix : 이미지 사이즈 경고 해결

src/app/main/products/[productId]/info/_blocks/SimpleInfoWithStoreSection/index.tsx, src/app/main/products/[productId]/layout.tsx, src/global/AlertContainer/ToastContainer.tsx, src/shared/atoms/alert.ts, src/shared/hooks/useToastNewVer.ts
> #584 
- 페이지 헤더 스토어명 노출
- 페이지 이미지 하단 스토어명 노출
- 페이지를 이동하여도 남아있는 토스트메세지 수정
https://github.com/user-attachments/assets/77e97686-2f97-4acc-82c4-09542c8fb604
- 토스트 메세지 무한 렌더링 버그 해결
*Before
*After
토스트 메세지 UI 위치를 수정하려고 했으나, 정상적인 위치에서 렌더링 되는 것을 확인하였습니다.
다만, 신경쓰이는 부분은 페이지 로딩에 따라서 토스트메세지의 x값이 바뀌는 거 같은데
이 부분은 조금 더 지켜보며 테스팅 해볼게요. 추후에도 x값이 footer로 붙어버리는 이슈가 발생되면 다시 한번 수정 보도록하겠습니다 👍
=> 🐛 Fix : 상품상세페이지 UI 관련 이슈 해결

src/blocks/main/(list)/SortingFilterSection/FilterButton.tsx
=> 🐛 Fix :삭제 시 필터는 모달 활성화 X

package.json, src/app/main/products/[productId]/info/_blocks/BoardDetailsSection.tsx, src/app/main/products/[productId]/review/page.tsx, yarn.lock
#633
>xss 를 고려해서 마크다운으로 내용을 보여줌
=> 🐛 fix:: 상세페이지 수정
